# Generated by Django 3.0.5 on 2021-04-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuri', '0002_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
